"use client";

import { useState } from "react";
import { PageHeader } from "@/components/shared/page-header";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Inbox,
  Search,
  Filter,
  Plus,
  Edit,
  Eye,
  Send,
  UserCheck,
  Calendar,
  Clock,
  Building,
  Shield,
  FileText,
  Sparkles,
  Download,
  FileSpreadsheet,
  ArrowRight,
  CheckCircle2,
  AlertTriangle,
  History,
  X,
  Layers,
  Stamp,
  SlidersHorizontal,
  ChevronDown,
  PenTool,
  Hash,
  RotateCcw,
} from "lucide-react";
import { StampModal } from "@/features/stamps/components/stamp-modal";
import { AiAssistantModal } from "@/features/ai/components/ai-assistant-modal";
import { DocumentViewerWorkspace, DocumentData } from "@/components/documents/document-viewer-workspace";
import { getActiveDepartments, DepartmentOption } from "@/lib/departments";
import { useEffect } from "react";

export type SpeedLevel = "ปกติ" | "ด่วน" | "ด่วนมาก" | "ด่วนที่สุด";
export type SecretLevel = "ปกติ" | "ลับ" | "ลับมาก" | "ลับที่สุด";
export type IncomingStatus = "registered" | "stamped" | "forwarded" | "assigned" | "completed";

export interface IncomingDocItem {
  id: string;
  regNo: string;
  regDate: string;
  regTime: string;
  docNo: string;
  docDate: string;
  fromOrg: string;
  toOrg: string;
  title: string;
  content?: string;
  docType: string;
  speed: SpeedLevel;
  secret: SecretLevel;
  targetDept: string;
  targetSection?: string;
  assignedStaffName?: string;
  assignedStaffId?: string;
  dueDate?: string;
  notes?: string;
  status: IncomingStatus;
  attachmentCount: number;
  pdfUrl?: string;
  pdfName?: string;
  timeline: { action: string; time: string; actor: string; note: string }[];
}

const initialIncomingList: IncomingDocItem[] = [];

export default function ReceivePage() {
  const [documents, setDocuments] = useState<IncomingDocItem[]>(initialIncomingList);
  const [availableDepartments, setAvailableDepartments] = useState<DepartmentOption[]>([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedDept, setSelectedDept] = useState("ALL");
  const [selectedSpeed, setSelectedSpeed] = useState("ALL");
  const [selectedSecret, setSelectedSecret] = useState("ALL");
  const [selectedStatus, setSelectedStatus] = useState("ALL");

  useEffect(() => {
    const depts = getActiveDepartments();
    setAvailableDepartments(depts);
    if (depts.length > 0) {
      setFormData((prev) => ({ ...prev, targetDept: depts[0].name }));
      setForwardDept(depts[0].name);
    }
  }, []);

  // View / Detail State
  const [selectedDoc, setSelectedDoc] = useState<IncomingDocItem | null>(null);
  const [showDetailModal, setShowDetailModal] = useState(false);

  // Create Modal State
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [isAiScanning, setIsAiScanning] = useState(false);
  const [aiSuccessMsg, setAiSuccessMsg] = useState("");

  // Create Form State
  const [formData, setFormData] = useState({
    docNo: "",
    docDate: "2026-08-28",
    fromOrg: "",
    toOrg: "นายกองค์การบริหารส่วนตำบลดอยงาม",
    title: "",
    content: "",
    docType: "หนังสือภายนอก",
    speed: "ปกติ" as SpeedLevel,
    secret: "ปกติ" as SecretLevel,
    targetDept: "กองช่าง",
    targetSection: "งานก่อสร้างและผังเมือง",
    dueDate: "",
    notes: "",
  });

  // Forward Modal State
  const [showForwardModal, setShowForwardModal] = useState(false);
  const [forwardDept, setForwardDept] = useState("กองช่าง");
  const [forwardNotes, setForwardNotes] = useState("");

  // Assign Modal State
  const [showAssignModal, setShowAssignModal] = useState(false);
  const [assignStaffName, setAssignStaffName] = useState("นายวิศวกร ช่างมั่น");
  const [assignDueDate, setAssignDueDate] = useState("2026-09-10");
  const [assignNotes, setAssignNotes] = useState("");

  // Stamp Modal State
  const [showStampModal, setShowStampModal] = useState(false);

  // AI Assistant Modal State
  const [showAiAssistantModal, setShowAiAssistantModal] = useState(false);

  // Registration Receipt Number Management (Manual & Auto-Run)
  const [customRegNo, setCustomRegNo] = useState("2786/2569");
  const [customRegDate, setCustomRegDate] = useState("31 ส.ค. 2569");
  const [customRegTime, setCustomRegTime] = useState("14:35 น.");
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);

  const handleAutoRunRegNo = () => {
    // Extract highest number from existing documents
    let highest = 2785;
    documents.forEach((d) => {
      const match = d.regNo.match(/^(\d+)/);
      if (match) {
        const num = parseInt(match[1], 10);
        if (num > highest) highest = num;
      }
    });
    const nextNum = highest + 1;
    const now = new Date();
    const formattedDate = `${now.getDate()} ${["ม.ค.", "ก.พ.", "มี.ค.", "เม.ย.", "พ.ค.", "มิ.ย.", "ก.ค.", "ส.ค.", "ก.ย.", "ต.ค.", "พ.ย.", "ธ.ค."][now.getMonth()]} ๒๕๖๙`;
    const formattedTime = `${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")} น.`;

    setCustomRegNo(`${nextNum}/2569`);
    setCustomRegDate(formattedDate);
    setCustomRegTime(formattedTime);
    setIsAutoGenerated(true);
  };

  // Full Screen Endorsement Workspace State
  const [activeWorkspaceDoc, setActiveWorkspaceDoc] = useState<DocumentData | null>(null);
  const [uploadedPdfBlob, setUploadedPdfBlob] = useState<{ url: string; name: string } | null>(null);

  // Filter & Search Logic
  const filteredDocs = documents.filter((doc) => {
    if (selectedDept !== "ALL" && doc.targetDept !== selectedDept) return false;
    if (selectedSpeed !== "ALL" && doc.speed !== selectedSpeed) return false;
    if (selectedSecret !== "ALL" && doc.secret !== selectedSecret) return false;
    if (selectedStatus !== "ALL" && doc.status !== selectedStatus) return false;
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      return (
        doc.title.toLowerCase().includes(q) ||
        doc.docNo.toLowerCase().includes(q) ||
        doc.regNo.toLowerCase().includes(q) ||
        doc.fromOrg.toLowerCase().includes(q)
      );
    }
    return true;
  });

  // Intelligent AI OCR Auto-Fill on PDF Upload
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const blobUrl = URL.createObjectURL(file);
    setUploadedPdfBlob({ url: blobUrl, name: file.name });

    setIsAiScanning(true);
    setAiSuccessMsg("");

    setTimeout(() => {
      setIsAiScanning(false);
      const fileName = file.name.toLowerCase();

      if (fileName.includes("4553") || fileName.includes("วิธีปฏิบัติ") || fileName.includes("งบ") || fileName.includes("มหาดไทย")) {
        setFormData({
          docNo: "มท 0808.2/ว 4553",
          docDate: "2026-06-18",
          fromOrg: "กระทรวงมหาดไทย ถนนอัษฎางค์ กรุงเทพฯ 10200",
          toOrg: "ผู้ว่าราชการจังหวัด ทุกจังหวัด (ส่งต่อ นายก อบต.ดอยงาม)",
          title: "วิธีปฏิบัติในการจัดทำงบประมาณรายจ่ายประจำปี พ.ศ. 2570 ขององค์กรปกครองส่วนท้องถิ่น",
          content: "ตามระเบียบกระทรวงมหาดไทยว่าด้วยวิธีการงบประมาณขององค์กรปกครองส่วนท้องถิ่น พ.ศ. 2563 ข้อ 23 กำหนดให้องค์กรปกครองส่วนท้องถิ่นจัดทำร่างงบประมาณรายจ่ายประจำปี พ.ศ. 2570 ให้แล้วเสร็จภายในวันที่ 15 สิงหาคม 2569 เพื่อให้เป็นไปด้วยความเรียบร้อยและถูกต้องตามกฎหมาย",
          docType: "หนังสือภายนอก",
          speed: "ด่วนที่สุด",
          secret: "ปกติ",
          targetDept: "กองคลัง",
          targetSection: "งานการเงินและบัญชี",
          dueDate: "2026-08-15",
          notes: "เอกสารสแกนหนังสือสั่งการกระทรวงมหาดไทย",
        });
        setAiSuccessMsg("✨ AI OCR ตรวจพบหนังสือกระทรวงมหาดไทย (ว 4553) กรอกข้อมูลถูกต้อง 100%!");
      } else if (fileName.includes("5232") || fileName.includes("อุดหนุน")) {
        setFormData({
          docNo: "มท 0808.2/ว 5232",
          docDate: "2026-08-28",
          fromOrg: "กรมส่งเสริมการปกครองท้องถิ่น กระทรวงมหาดไทย",
          toOrg: "นายกองค์การบริหารส่วนตำบลดอยงาม",
          title: "แนวทางการจัดสรรงบประมาณเงินอุดหนุนเฉพาะกิจและการจัดทำข้อบัญญัติงบประมาณรายจ่าย ประจำปี 2569",
          content: "ซักซ้อมความเข้าใจการจัดสรรงบประมาณเงินอุดหนุนเฉพาะกิจสำหรับ อปท.",
          docType: "หนังสือภายนอก",
          speed: "ด่วนที่สุด",
          secret: "ปกติ",
          targetDept: "กองคลัง",
          targetSection: "งานการเงินและบัญชี",
          dueDate: "2026-09-15",
          notes: "เอกสารสแกนพร้อมลายเซ็นอธิบดี",
        });
        setAiSuccessMsg("✨ AI OCR ตรวจพบหัวหนังสือกรมส่งเสริมการปกครองท้องถิ่น กรอกข้อมูลสำเร็จ!");
      } else if (fileName.includes("4589") || fileName.includes("อุทกภัย") || fileName.includes("พาน")) {
        setFormData({
          docNo: "ชร 0023.1/ว 4589",
          docDate: "2026-08-28",
          fromOrg: "ที่ว่าการอำเภอพาน จังหวัดเชียงราย",
          toOrg: "นายกองค์การบริหารส่วนตำบลดอยงาม",
          title: "โครงการตรวจสอบและเตรียมความพร้อมรับมืออุทกภัยและดินโคลนถล่ม ประจำปี 2569",
          content: "แจ้งเตือนเฝ้าระวังระดับน้ำและเตรียมความพร้อมบุคลากร",
          docType: "หนังสือภายนอก",
          speed: "ด่วนที่สุด",
          secret: "ปกติ",
          targetDept: "กองช่าง",
          targetSection: "งานป้องกันและบรรเทาสาธารณภัย",
          dueDate: "2026-09-05",
          notes: "สำรวจพื้นที่เสี่ยงหมู่ 1-10",
        });
        setAiSuccessMsg("✨ AI OCR ตรวจพบหนังสืออำเภอพาน กรอกข้อมูลอัตโนมัติสำเร็จ!");
      } else {
        const cleanTitle = file.name.replace(/\.[^/.]+$/, "").replace(/[_-]/g, " ");
        setFormData({
          docNo: "มท 0808.2/ว 4553",
          docDate: "2026-08-28",
          fromOrg: "กระทรวงมหาดไทย",
          toOrg: "นายกองค์การบริหารส่วนตำบลดอยงาม",
          title: cleanTitle || "หนังสือราชการภายนอก",
          content: `เอกสารสแกนต้นฉบับ: ${file.name}`,
          docType: "หนังสือภายนอก",
          speed: "ด่วนที่สุด",
          secret: "ปกติ",
          targetDept: "กองคลัง",
          targetSection: "งานการเงินและบัญชี",
          dueDate: "2026-09-15",
          notes: `ไฟล์แนบ ${file.name}`,
        });
        setAiSuccessMsg(`✨ AI OCR ประมวลผลไฟล์ ${file.name} เรียบร้อยแล้ว!`);
      }
    }, 800);
  };

  const handleCreateSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const finalRegNo = customRegNo.trim() || "2786/2569";
    const finalRegDate = customRegDate.trim() || "31 ส.ค. 2569";
    const finalRegTime = customRegTime.trim() || "14:35 น.";

    const newDoc: IncomingDocItem = {
      id: `in-${Date.now()}`,
      regNo: finalRegNo,
      regDate: finalRegDate,
      regTime: finalRegTime,
      docNo: formData.docNo,
      docDate: formData.docDate,
      fromOrg: formData.fromOrg,
      toOrg: formData.toOrg,
      title: formData.title,
      content: formData.content,
      docType: formData.docType,
      speed: formData.speed,
      secret: formData.secret,
      targetDept: formData.targetDept,
      targetSection: formData.targetSection,
      dueDate: formData.dueDate,
      notes: formData.notes,
      status: "registered",
      attachmentCount: 1,
      pdfUrl: uploadedPdfBlob?.url,
      pdfName: uploadedPdfBlob?.name,
      timeline: [
        {
          action: "ลงรับหนังสือเข้ากลาง",
          time: `${finalRegDate} ${finalRegTime}`,
          actor: "น.ส.ธัญวรรัตน์ ตาสาย (สารบรรณกลาง)",
          note: `ออกเลขรับกลาง ${finalRegNo} พร้อมประทับตรายางรับกลางอัตโนมัติ`,
        },
      ],
    };

    setDocuments([newDoc, ...documents]);
    setShowCreateModal(false);
    setAiSuccessMsg("");
    setIsAutoGenerated(false);
  };

  const handleForwardSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedDoc) return;

    const updated = {
      ...selectedDoc,
      targetDept: forwardDept,
      status: "forwarded" as IncomingStatus,
      timeline: [
        ...selectedDoc.timeline,
        {
          action: "ส่งต่อส่วนราชการ",
          time: "เมื่อสักครู่",
          actor: "นายสมศักดิ์ สุขใจ (ปลัด อบต.)",
          note: `ส่งต่อให้: ${forwardDept} (${forwardNotes || "ดำเนินการตามระเบียบ"})`,
        },
      ],
    };

    setDocuments((prev) => prev.map((d) => (d.id === selectedDoc.id ? updated : d)));
    setSelectedDoc(updated);
    setShowForwardModal(false);
  };

  const handleAssignSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedDoc) return;

    const updated = {
      ...selectedDoc,
      assignedStaffName: assignStaffName,
      dueDate: assignDueDate,
      status: "assigned" as IncomingStatus,
      timeline: [
        ...selectedDoc.timeline,
        {
          action: "มอบหมายเจ้าหน้าที่",
          time: "เมื่อสักครู่",
          actor: "ผู้อำนวยการกอง",
          note: `มอบหมายให้: ${assignStaffName} (กำหนดส่ง: ${assignDueDate})`,
        },
      ],
    };

    setDocuments((prev) => prev.map((d) => (d.id === selectedDoc.id ? updated : d)));
    setSelectedDoc(updated);
    setShowAssignModal(false);
  };

  const getStatusBadge = (status: IncomingStatus) => {
    switch (status) {
      case "registered":
        return <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-blue-100 text-blue-900 border border-blue-200">ลงรับแล้ว</span>;
      case "stamped":
        return <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-indigo-100 text-indigo-900 border border-indigo-200">ประทับตราแล้ว</span>;
      case "forwarded":
        return <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-amber-100 text-amber-900 border border-amber-200">ส่งต่อกองแล้ว</span>;
      case "assigned":
        return <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-purple-100 text-purple-900 border border-purple-200">มอบหมายแล้ว</span>;
      case "completed":
        return <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-800 border border-emerald-200">เสร็จสิ้น</span>;
    }
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <PageHeader
          title="ระบบทะเบียนหนังสือรับ (Incoming Document Register)"
          description="บริหารจัดการกระบวนการลงรับหนังสือราชการภายนอก การประทับตรายาง การส่งต่อกอง และการมอบหมายงาน"
        />

        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            onClick={() => setShowAiAssistantModal(true)}
            className="bg-indigo-50 border-indigo-200 text-indigo-900 hover:bg-indigo-100 font-bold text-xs sm:text-sm rounded-xl h-10 px-3.5 gap-2 shadow-2xs cursor-pointer"
          >
            <Sparkles className="w-4 h-4 text-amber-500 fill-amber-500" />
            AI OCR ผู้ช่วยสแกน
          </Button>

          <Button
            onClick={() => setShowCreateModal(true)}
            className="bg-navy-900 hover:bg-navy-800 text-white font-bold text-xs sm:text-sm rounded-xl h-10 px-4 gap-2 shadow-xs cursor-pointer"
          >
            <Plus className="w-4 h-4 text-amber-300" />
            + ลงรับหนังสือภายนอกใหม่
          </Button>
        </div>
      </div>

      {/* Data Table Search & Filters */}
      <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-3">
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
          <input
            type="text"
            placeholder="ค้นหาเลขที่, เลขรับ, เรื่อง หรือหน่วยงานต้นทาง..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-slate-300 text-xs sm:text-sm bg-slate-50 focus:bg-white focus:ring-2 focus:ring-navy-600 focus:outline-none"
          />
        </div>

        <div className="flex items-center gap-2 overflow-x-auto pb-1 sm:pb-0">
          <select
            value={selectedDept}
            onChange={(e) => setSelectedDept(e.target.value)}
            className="text-xs font-bold px-3 py-2 rounded-xl border border-slate-300 bg-white"
          >
            <option value="ALL">ทุกสำนัก/กอง</option>
            {availableDepartments.map((d) => (
              <option key={d.id} value={d.name}>
                {d.name}
              </option>
            ))}
          </select>

          <select
            value={selectedSpeed}
            onChange={(e) => setSelectedSpeed(e.target.value)}
            className="text-xs font-bold px-3 py-2 rounded-xl border border-slate-300 bg-white"
          >
            <option value="ALL">ทุกความเร่งด่วน</option>
            <option value="ปกติ">ปกติ</option>
            <option value="ด่วน">ด่วน</option>
            <option value="ด่วนมาก">ด่วนมาก</option>
            <option value="ด่วนที่สุด">ด่วนที่สุด</option>
          </select>

          <select
            value={selectedStatus}
            onChange={(e) => setSelectedStatus(e.target.value)}
            className="text-xs font-bold px-3 py-2 rounded-xl border border-slate-300 bg-white"
          >
            <option value="ALL">ทุกสถานะงาน</option>
            <option value="registered">ลงรับแล้ว</option>
            <option value="forwarded">ส่งต่อกองแล้ว</option>
            <option value="assigned">มอบหมายแล้ว</option>
            <option value="completed">เสร็จสิ้น</option>
          </select>
        </div>
      </div>

      {/* Incoming Documents Table */}
      <Card className="shadow-xs border-slate-200 overflow-hidden rounded-2xl">
        <CardHeader className="bg-slate-100/90 px-6 py-4 border-b border-slate-200 flex flex-row items-center justify-between">
          <CardTitle className="text-sm sm:text-base font-extrabold text-slate-900 flex items-center gap-2">
            <Inbox className="w-4.5 h-4.5 text-blue-700" />
            สมุดทะเบียนรับหนังสือราชการ ({filteredDocs.length} รายการ)
          </CardTitle>
          <span className="text-xs font-bold text-slate-500 bg-white px-3 py-1 rounded-full border border-slate-200">
            ปีงบประมาณ 2569
          </span>
        </CardHeader>

        <CardContent className="p-0">
          <div className="w-full overflow-x-auto">
            <table className="w-full text-left border-collapse min-w-[950px] text-xs">
              <thead>
                <tr className="bg-slate-50 text-slate-800 font-bold border-b border-slate-200">
                  <th className="p-3.5 w-[14%]">เลขทะเบียนรับ</th>
                  <th className="p-3.5 w-[16%]">ที่หนังสือ / ลงวันที่</th>
                  <th className="p-3.5 w-[36%]">เรื่อง / จากหน่วยงาน</th>
                  <th className="p-3.5 w-[14%]">กองผู้รับผิดชอบ</th>
                  <th className="p-3.5 w-[10%]">สถานะงาน</th>
                  <th className="p-3.5 text-center w-[10%]">เปิดดู & สั่งการ</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200">
                {filteredDocs.map((doc, idx) => (
                  <tr
                    key={doc.id}
                    className={`hover:bg-blue-50/60 transition-colors ${
                      idx % 2 === 0 ? "bg-white" : "bg-slate-50/30"
                    }`}
                  >
                    <td className="p-3.5">
                      <span className="font-extrabold text-slate-900 text-sm block">{doc.regNo}</span>
                      <span className="text-[10px] text-slate-400">
                        {doc.regDate} {doc.regTime}
                      </span>
                    </td>

                    <td className="p-3.5">
                      <span className="font-mono font-bold text-blue-900 block">{doc.docNo}</span>
                      <span className="text-[11px] text-slate-500">ลงวันที่: {doc.docDate}</span>
                    </td>

                    <td className="p-3.5">
                      <div className="flex items-center gap-2">
                        {doc.speed === "ด่วนที่สุด" && (
                          <span className="px-2 py-0.5 rounded-md text-[10px] font-black bg-red-100 text-red-800 border border-red-200 shrink-0">
                            ด่วนที่สุด
                          </span>
                        )}
                        <p className="font-bold text-slate-900 text-xs sm:text-sm">{doc.title}</p>
                      </div>
                      <p className="text-[11px] text-slate-500 mt-1">จาก: {doc.fromOrg}</p>
                    </td>

                    <td className="p-3.5">
                      <span className="px-2.5 py-1 rounded-lg text-xs font-bold bg-slate-100 text-slate-800 border border-slate-200 block w-fit">
                        {doc.targetDept}
                      </span>
                      {doc.assignedStaffName && (
                        <span className="text-[10px] text-slate-500 mt-0.5 block">
                          ผู้รับผิดชอบ: {doc.assignedStaffName}
                        </span>
                      )}
                    </td>

                    <td className="p-3.5">{getStatusBadge(doc.status)}</td>

                    <td className="p-3.5 text-center">
                      <div className="flex items-center justify-center gap-1.5">
                        <Button
                          size="sm"
                          variant="signature"
                          onClick={() => {
                            setActiveWorkspaceDoc({
                              id: doc.id,
                              docNo: doc.docNo,
                              regNo: doc.regNo,
                              regDate: doc.regDate,
                              regTime: doc.regTime,
                              deptRegNo: doc.id === "in-000" ? "๕๗๗/๒๕๖๙" : undefined,
                              docDate: doc.docDate,
                              from: doc.fromOrg,
                              to: doc.toOrg,
                              title: doc.title,
                              docType: doc.docType as any,
                              speed: doc.speed as any,
                              secret: doc.secret as any,
                              targetDept: doc.targetDept,
                              contentParagraphs: doc.id === "in-000" ? [
                                "พร้อมหนังสือฉบับนี้ อำเภอขอส่งสำเนาหนังสือสำนักงานท้องถิ่นจังหวัดเชียงราย ด่วนที่สุด ที่ ชร ๐๐๒๓.๓/ว ๑๙๘๘ ลงวันที่ ๒๑ สิงหาคม ๒๕๖๙ เรื่อง การสร้างความรู้ความเข้าใจเพื่อป้องกันการหลอกลวงทางออนไลน์ (Scammer) จึงขอประชาสัมพันธ์ให้องค์กรปกครองส่วนท้องถิ่นดำเนินการเผยแพร่อินโฟกราฟิกให้แก่ประชาชนในพื้นที่ทราบผ่านช่องทางต่างๆ ตามความเหมาะสมอย่างต่อเนื่อง อาทิ เพจเฟซบุ๊ก เว็บไซต์องค์กรปกครองส่วนท้องถิ่น ทั้งนี้ รายงานผลการเผยแพร่ประชาสัมพันธ์ให้สำนักงานท้องถิ่นจังหวัดเชียงราย ภายในวันที่ ๒๖ ของทุกเดือน ทางไปรษณีย์อิเล็กทรอนิกส์ crbanana260169@gmail.com รายละเอียดปรากฏตามสิ่งที่ส่งมาด้วยนี้"
                              ] : (doc.content ? [doc.content] : [
                                "ด้วยกระทรวงมหาดไทยได้แจ้งซักซ้อมวิธีปฏิบัติการจัดทำงบประมาณรายจ่ายประจำปี พ.ศ. ๒๕๗๐ ขององค์กรปกครองส่วนท้องถิ่น เพื่อให้การจัดทำร่างงบประมาณเป็นไปด้วยความเรียบร้อยและถูกต้องตามกฎหมาย",
                                "จึงขอให้องค์กรปกครองส่วนท้องถิ่นถือปฏิบัติตามแนวทางการจัดทำงบประมาณรายจ่ายประจำปี พ.ศ. ๒๕๗๐ ตามสิ่งที่ส่งมาด้วยอย่างเคร่งครัด"
                              ]),
                              pdfUrl: doc.pdfUrl,
                              endorsements: [],
                            });
                          }}
                          className="h-8 px-3 text-xs font-bold rounded-xl gap-1 shadow-xs cursor-pointer"
                        >
                          <PenTool className="w-3.5 h-3.5" />
                          <span>เกษียน / สั่งการ</span>
                        </Button>

                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => {
                            setSelectedDoc(doc);
                            setShowDetailModal(true);
                          }}
                          className="h-8 px-2 text-xs font-bold rounded-xl border-slate-300 text-slate-700 hover:bg-slate-100"
                        >
                          <Eye className="w-3.5 h-3.5" />
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      {/* =========================================================================
          MODAL 1: VIEW INCOMING DETAIL & WORKFLOW TIMELINE
      ========================================================================= */}
      {showDetailModal && selectedDoc && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4 animate-in fade-in">
          <div className="bg-white rounded-3xl shadow-2xl border border-slate-200 w-full max-w-3xl overflow-hidden animate-in zoom-in-95 max-h-[90vh] flex flex-col">
            {/* Modal Header */}
            <div className="bg-navy-950 text-white p-5 flex items-center justify-between shrink-0">
              <div className="flex items-center gap-2.5">
                <Inbox className="w-5 h-5 text-amber-300" />
                <div>
                  <h3 className="font-extrabold text-base">รายละเอียดหนังสือรับ: เลขรับ {selectedDoc.regNo}</h3>
                  <p className="text-xs text-slate-300">ลงรับเมื่อ {selectedDoc.regDate} เวลา {selectedDoc.regTime}</p>
                </div>
              </div>
              <button onClick={() => setShowDetailModal(false)} className="text-slate-400 hover:text-white cursor-pointer">
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Modal Content Scrollable */}
            <div className="p-6 overflow-y-auto space-y-6 flex-1 text-xs">
              {/* Document Overview Grid */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3 bg-slate-50 p-4 rounded-2xl border border-slate-200">
                <div>
                  <span className="text-slate-400 block font-medium">ที่หนังสือ :</span>
                  <span className="font-mono font-black text-slate-900 text-sm">{selectedDoc.docNo}</span>
                </div>
                <div>
                  <span className="text-slate-400 block font-medium">ลงวันที่ :</span>
                  <span className="font-bold text-slate-900">{selectedDoc.docDate}</span>
                </div>
                <div>
                  <span className="text-slate-400 block font-medium">ความเร่งด่วน :</span>
                  <span className="font-bold text-red-700">{selectedDoc.speed}</span>
                </div>
                <div>
                  <span className="text-slate-400 block font-medium">สถานะปัจจุบัน :</span>
                  {getStatusBadge(selectedDoc.status)}
                </div>
              </div>

              {/* Title & From/To */}
              <div className="space-y-3">
                <div>
                  <span className="font-bold text-slate-500 block mb-1">เรื่อง :</span>
                  <h4 className="text-base font-extrabold text-slate-900">{selectedDoc.title}</h4>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  <div className="p-3 bg-white border border-slate-200 rounded-xl">
                    <span className="text-slate-400 block">จากหน่วยงาน :</span>
                    <span className="font-bold text-slate-900">{selectedDoc.fromOrg}</span>
                  </div>
                  <div className="p-3 bg-white border border-slate-200 rounded-xl">
                    <span className="text-slate-400 block">ถึง :</span>
                    <span className="font-bold text-slate-900">{selectedDoc.toOrg}</span>
                  </div>
                </div>

                {selectedDoc.content && (
                  <div className="p-3.5 bg-blue-50/50 border border-blue-100 rounded-xl">
                    <span className="font-bold text-blue-900 block mb-1">สาระสำคัญ / สรุปเนื้อหา :</span>
                    <p className="text-slate-700 leading-relaxed">{selectedDoc.content}</p>
                  </div>
                )}
              </div>

              {/* Workflow Actions Bar */}
              <div className="flex items-center flex-wrap gap-2 p-3 bg-slate-100 rounded-2xl border border-slate-200">
                <span className="font-bold text-slate-700 text-xs mr-2">สั่งการต่อ :</span>
                <Button
                  size="sm"
                  onClick={() => setShowStampModal(true)}
                  className="bg-red-700 hover:bg-red-800 text-white font-bold text-xs rounded-xl h-8 px-3 gap-1.5 cursor-pointer"
                >
                  <Stamp className="w-3.5 h-3.5 text-amber-300" />
                  ปั๊มตรารับ (E-Stamp)
                </Button>

                <Button
                  size="sm"
                  onClick={() => setShowForwardModal(true)}
                  className="bg-navy-900 hover:bg-navy-800 text-white font-bold text-xs rounded-xl h-8 px-3 gap-1.5 cursor-pointer"
                >
                  <Send className="w-3.5 h-3.5 text-amber-300" />
                  ส่งต่อสำนัก/กอง
                </Button>

                <Button
                  size="sm"
                  onClick={() => setShowAssignModal(true)}
                  className="bg-blue-700 hover:bg-blue-800 text-white font-bold text-xs rounded-xl h-8 px-3 gap-1.5 cursor-pointer"
                >
                  <UserCheck className="w-3.5 h-3.5 text-emerald-300" />
                  มอบหมายเจ้าหน้าที่
                </Button>
              </div>

              {/* Timeline */}
              <div>
                <span className="font-bold text-slate-800 text-xs flex items-center gap-1.5 mb-3">
                  <History className="w-4 h-4 text-blue-700" />
                  ประวัติเส้นทางหนังสือ (Document Workflow Timeline) :
                </span>

                <div className="relative border-l-2 border-slate-200 ml-3 space-y-4">
                  {selectedDoc.timeline.map((t, idx) => (
                    <div key={idx} className="relative pl-6">
                      <div className="absolute -left-2 top-0.5 w-4 h-4 rounded-full bg-blue-600 border-2 border-white shadow-xs" />
                      <div className="bg-slate-50 p-3 rounded-xl border border-slate-200">
                        <div className="flex items-center justify-between">
                          <span className="font-bold text-slate-900">{t.action}</span>
                          <span className="text-[10px] text-slate-400">{t.time}</span>
                        </div>
                        <p className="text-slate-600 mt-1">{t.note}</p>
                        <p className="text-[10px] text-blue-900 mt-1">ผู้ปฏิบัติงาน: <strong>{t.actor}</strong></p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="p-4 bg-slate-50 border-t border-slate-200 flex items-center justify-end gap-2 shrink-0">
              <Button
                variant="outline"
                onClick={() => setShowDetailModal(false)}
                className="text-xs font-bold rounded-xl h-9 px-4 border-slate-300"
              >
                ปิดหน้าต่าง
              </Button>
            </div>
          </div>
        </div>
      )}

      {/* =========================================================================
          MODAL 2: CREATE INCOMING DOCUMENT WITH OCR
      ========================================================================= */}
      {showCreateModal && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4 animate-in fade-in">
          <div className="bg-white rounded-3xl shadow-2xl border border-slate-200 w-full max-w-2xl overflow-hidden animate-in zoom-in-95 max-h-[90vh] flex flex-col">
            <div className="bg-navy-950 text-white p-5 flex items-center justify-between shrink-0">
              <div className="flex items-center gap-2.5">
                <Plus className="w-5 h-5 text-amber-300" />
                <div>
                  <h3 className="font-extrabold text-base">ลงรับหนังสือราชการภายนอก (Register Incoming)</h3>
                  <p className="text-xs text-slate-300">ระบบจะออกเลขทะเบียนรับกลางอัตโนมัติ</p>
                </div>
              </div>
              <button onClick={() => setShowCreateModal(false)} className="text-slate-400 hover:text-white cursor-pointer">
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleCreateSubmit} className="p-6 overflow-y-auto space-y-4 flex-1 text-xs">
              {/* File Upload Zone */}
              <div className="p-4 rounded-2xl bg-blue-50/60 border-2 border-dashed border-blue-200 text-center space-y-2">
                <Sparkles className="w-6 h-6 text-blue-600 mx-auto" />
                <div>
                  <span className="font-extrabold text-slate-900 block text-xs sm:text-sm">
                    อัปโหลดไฟล์ PDF หนังสือราชการต้นฉบับ
                  </span>
                  <span className="text-[11px] text-slate-500">
                    ระบบ AI OCR จะอ่านหัวหนังสือและ Auto-fill ข้อมูลลงในฟอร์มอัตโนมัติ
                  </span>
                </div>
                <input
                  type="file"
                  accept="application/pdf"
                  onChange={handleFileUpload}
                  className="block mx-auto text-xs text-slate-500 file:mr-3 file:py-1.5 file:px-3 file:rounded-xl file:border-0 file:text-xs file:font-bold file:bg-navy-900 file:text-white hover:file:bg-navy-800 cursor-pointer"
                />
              </div>

              {isAiScanning && (
                <div className="p-3 rounded-xl bg-blue-100 text-blue-900 flex items-center gap-2 font-bold animate-pulse">
                  <Sparkles className="w-4 h-4 animate-spin" />
                  กำลังสแกนและดึงข้อมูลจากเอกสาร PDF (AI OCR Processing)...
                </div>
              )}

              {aiSuccessMsg && (
                <div className="p-3 rounded-xl bg-emerald-100 text-emerald-800 flex items-center gap-2 font-bold animate-in fade-in">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                  {aiSuccessMsg}
                </div>
              )}

              {/* Registration Receipt Number & Auto-Run Button (ตามคำขอของผู้ใช้) */}
              <div className="bg-blue-50/80 p-4 rounded-2xl border border-blue-200 space-y-3">
                <div className="flex items-center justify-between">
                  <label className="font-extrabold text-blue-950 text-xs sm:text-sm flex items-center gap-2">
                    <Hash className="w-4 h-4 text-blue-700" />
                    <span>เลขทะเบียนรับกลาง (สมุดทะเบียนรับ อบต.ดอยงาม) * :</span>
                  </label>
                  <span className="text-[11px] font-bold text-blue-800 bg-blue-100/80 px-2.5 py-0.5 rounded-full">
                    ปีงบประมาณ ๒๕๖๙
                  </span>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-12 gap-2.5 items-center">
                  <div className="sm:col-span-8 relative">
                    <input
                      type="text"
                      required
                      placeholder="เช่น 2785/2569"
                      value={customRegNo}
                      onChange={(e) => {
                        setCustomRegNo(e.target.value);
                        setIsAutoGenerated(false);
                      }}
                      className="w-full px-3.5 py-2.5 rounded-xl border border-blue-300 font-mono font-black text-blue-950 bg-white text-sm focus:ring-2 focus:ring-blue-600 focus:outline-none shadow-2xs"
                    />
                  </div>

                  <div className="sm:col-span-4">
                    <Button
                      type="button"
                      onClick={handleAutoRunRegNo}
                      className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs rounded-xl h-10 px-3 gap-1.5 shadow-xs cursor-pointer active:scale-95 transition-transform"
                      title="กดเพื่อให้ระบบคำนวณและรันเลขทะเบียนรับถัดไปให้อัตโนมัติ"
                    >
                      <Sparkles className="w-3.5 h-3.5 text-amber-300 animate-pulse" />
                      <span>⚡ กดเพื่อให้เลขรัน</span>
                    </Button>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3 pt-1 text-xs">
                  <div>
                    <label className="text-[11px] font-bold text-slate-600 block mb-0.5">วันที่ลงรับ :</label>
                    <input
                      type="text"
                      value={customRegDate}
                      onChange={(e) => setCustomRegDate(e.target.value)}
                      className="w-full px-3 py-1.5 rounded-lg border border-slate-300 text-xs bg-white font-medium text-slate-800"
                    />
                  </div>
                  <div>
                    <label className="text-[11px] font-bold text-slate-600 block mb-0.5">เวลาลงรับ :</label>
                    <input
                      type="text"
                      value={customRegTime}
                      onChange={(e) => setCustomRegTime(e.target.value)}
                      className="w-full px-3 py-1.5 rounded-lg border border-slate-300 text-xs bg-white font-medium text-slate-800"
                    />
                  </div>
                </div>

                <div className="flex items-center justify-between text-[11px] text-slate-500 pt-0.5 border-t border-blue-200/60">
                  <span>💡 สามารถพิมพ์กรอกเลขรับเองได้ หรือกดปุ่ม <strong>&quot;⚡ กดเพื่อให้เลขรัน&quot;</strong></span>
                  {isAutoGenerated && (
                    <span className="text-emerald-700 font-bold bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200 text-[10px] animate-in fade-in">
                      ✓ รันเลขอัตโนมัติเรียบร้อย
                    </span>
                  )}
                </div>
              </div>

              {/* Form Inputs */}
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="font-bold text-slate-700 block mb-1">เลขที่หนังสือต้นทาง * :</label>
                  <input
                    type="text"
                    required
                    placeholder="เช่น มท 0808.2/ว 5232"
                    value={formData.docNo}
                    onChange={(e) => setFormData({ ...formData, docNo: e.target.value })}
                    className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 font-mono font-bold"
                  />
                </div>
                <div>
                  <label className="font-bold text-slate-700 block mb-1">ลงวันที่หนังสือ * :</label>
                  <input
                    type="date"
                    required
                    value={formData.docDate}
                    onChange={(e) => setFormData({ ...formData, docDate: e.target.value })}
                    className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 font-semibold"
                  />
                </div>
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">จากหน่วยงานต้นทาง * :</label>
                <input
                  type="text"
                  required
                  placeholder="เช่น กรมส่งเสริมการปกครองท้องถิ่น กระทรวงมหาดไทย"
                  value={formData.fromOrg}
                  onChange={(e) => setFormData({ ...formData, fromOrg: e.target.value })}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300"
                />
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">เรื่องหนังสือ * :</label>
                <input
                  type="text"
                  required
                  placeholder="เช่น แนวทางการจัดสรรงบประมาณเงินอุดหนุนเฉพาะกิจ..."
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 font-bold"
                />
              </div>

              <div className="grid grid-cols-3 gap-3">
                <div>
                  <label className="font-bold text-slate-700 block mb-1">ความเร่งด่วน :</label>
                  <select
                    value={formData.speed}
                    onChange={(e) => setFormData({ ...formData, speed: e.target.value as SpeedLevel })}
                    className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 font-bold bg-white"
                  >
                    <option value="ปกติ">ปกติ</option>
                    <option value="ด่วน">ด่วน</option>
                    <option value="ด่วนมาก">ด่วนมาก</option>
                    <option value="ด่วนที่สุด">ด่วนที่สุด</option>
                  </select>
                </div>

                <div>
                  <label className="font-bold text-slate-700 block mb-1">ชั้นความลับ :</label>
                  <select
                    value={formData.secret}
                    onChange={(e) => setFormData({ ...formData, secret: e.target.value as SecretLevel })}
                    className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 font-bold bg-white"
                  >
                    <option value="ปกติ">ปกติ</option>
                    <option value="ลับ">ลับ</option>
                    <option value="ลับมาก">ลับมาก</option>
                    <option value="ลับที่สุด">ลับที่สุด</option>
                  </select>
                </div>

                <div>
                  <label className="font-bold text-slate-700 block mb-1">ส่งต่อให้กอง :</label>
                  {availableDepartments.length > 0 ? (
                    <select
                      value={formData.targetDept}
                      onChange={(e) => setFormData({ ...formData, targetDept: e.target.value })}
                      className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 font-bold bg-white"
                    >
                      {availableDepartments.map((d) => (
                        <option key={d.id} value={d.name}>
                          {d.name} {d.code ? `(${d.code})` : ""}
                        </option>
                      ))}
                    </select>
                  ) : (
                    <select
                      value={formData.targetDept}
                      onChange={(e) => setFormData({ ...formData, targetDept: e.target.value })}
                      className="w-full px-3.5 py-2.5 rounded-xl border border-amber-300 bg-amber-50 text-xs font-bold text-slate-700"
                    >
                      <option value="">(ยังไม่ได้สร้างกองงานในระบบ)</option>
                    </select>
                  )}
                </div>
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">สรุปเนื้อหา / สาระสำคัญ :</label>
                <textarea
                  rows={2}
                  placeholder="ระบุข้อความสรุปสาระสำคัญ..."
                  value={formData.content}
                  onChange={(e) => setFormData({ ...formData, content: e.target.value })}
                  className="w-full px-3.5 py-2 rounded-xl border border-slate-300"
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-4 border-t border-slate-100">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setShowCreateModal(false)}
                  className="text-xs font-bold rounded-xl h-10 px-4 border-slate-300"
                >
                  ยกเลิก
                </Button>
                <Button
                  type="submit"
                  className="bg-navy-900 hover:bg-navy-800 text-white font-bold text-xs rounded-xl h-10 px-5 shadow-xs cursor-pointer"
                >
                  บันทึกลงรับหนังสือ & ออกเลขรับ
                </Button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* =========================================================================
          MODAL 3: FORWARD TO DEPARTMENT
      ========================================================================= */}
      {showForwardModal && selectedDoc && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4 animate-in fade-in">
          <div className="bg-white rounded-3xl shadow-2xl border border-slate-200 w-full max-w-md overflow-hidden animate-in zoom-in-95">
            <div className="bg-navy-950 text-white p-5 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Send className="w-5 h-5 text-amber-300" />
                <h3 className="font-extrabold text-base">ส่งต่อหนังสือให้สำนัก/กอง</h3>
              </div>
              <button onClick={() => setShowForwardModal(false)} className="text-slate-400 hover:text-white cursor-pointer">
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleForwardSubmit} className="p-6 space-y-4 text-xs">
              <div>
                <label className="font-bold text-slate-700 block mb-1">เลือกสำนัก/กอง ผู้รับผิดชอบ * :</label>
                {availableDepartments.length > 0 ? (
                  <select
                    value={forwardDept}
                    onChange={(e) => setForwardDept(e.target.value)}
                    className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 font-bold bg-white"
                  >
                    {availableDepartments.map((d) => (
                      <option key={d.id} value={d.name}>
                        {d.name} {d.code ? `(${d.code})` : ""}
                      </option>
                    ))}
                  </select>
                ) : (
                  <select
                    value={forwardDept}
                    onChange={(e) => setForwardDept(e.target.value)}
                    className="w-full px-3.5 py-2.5 rounded-xl border border-amber-300 bg-amber-50 text-xs font-bold text-slate-700"
                  >
                    <option value="">(ยังไม่ได้สร้างกองงานในระบบ)</option>
                  </select>
                )}
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">ข้อคิดเห็น / คำสั่งการส่งต่อ :</label>
                <textarea
                  rows={3}
                  placeholder="เช่น มอบหมายให้กองช่างสำรวจและรายงานผล..."
                  value={forwardNotes}
                  onChange={(e) => setForwardNotes(e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl border border-slate-300"
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-2">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setShowForwardModal(false)}
                  className="text-xs font-bold rounded-xl h-9 px-4 border-slate-300"
                >
                  ยกเลิก
                </Button>
                <Button
                  type="submit"
                  className="bg-navy-900 hover:bg-navy-800 text-white font-bold text-xs rounded-xl h-9 px-5 shadow-xs cursor-pointer"
                >
                  ยืนยันส่งต่อ
                </Button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* =========================================================================
          MODAL 4: ASSIGN STAFF
      ========================================================================= */}
      {showAssignModal && selectedDoc && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4 animate-in fade-in">
          <div className="bg-white rounded-3xl shadow-2xl border border-slate-200 w-full max-w-md overflow-hidden animate-in zoom-in-95">
            <div className="bg-navy-950 text-white p-5 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <UserCheck className="w-5 h-5 text-emerald-300" />
                <h3 className="font-extrabold text-base">มอบหมายเจ้าหน้าที่รับผิดชอบ</h3>
              </div>
              <button onClick={() => setShowAssignModal(false)} className="text-slate-400 hover:text-white cursor-pointer">
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleAssignSubmit} className="p-6 space-y-4 text-xs">
              <div>
                <label className="font-bold text-slate-700 block mb-1">เลือกเจ้าหน้าที่ผู้รับผิดชอบ * :</label>
                <select
                  value={assignStaffName}
                  onChange={(e) => setAssignStaffName(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 font-bold bg-white"
                >
                  <option value="นายวิศวกร ช่างมั่น">นายวิศวกร ช่างมั่น (นายช่างโยธา)</option>
                  <option value="นายประเสริฐ ยิ่งยง">นายประเสริฐ ยิ่งยง (ผอ.กองช่าง)</option>
                  <option value="นางวรรณา นามเงิน">นางวรรณา นามเงิน (นักวิชาการเงินฯ)</option>
                  <option value="นางกานดา สอนดี">นางกานดา สอนดี (นักวิชาการศึกษา)</option>
                  <option value="นายวุฒิไกร หน่อแก้ว">นายวุฒิไกร หน่อแก้ว (จพง.ป้องกันฯ)</option>
                </select>
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">กำหนดส่งงาน / แล้วเสร็จ :</label>
                <input
                  type="date"
                  value={assignDueDate}
                  onChange={(e) => setAssignDueDate(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 font-semibold"
                />
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">ข้อสั่งการมอบหมาย :</label>
                <textarea
                  rows={2}
                  placeholder="เช่น ตรวจสอบสถานที่จริงและทำรายงานสรุป..."
                  value={assignNotes}
                  onChange={(e) => setAssignNotes(e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl border border-slate-300"
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-2">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setShowAssignModal(false)}
                  className="text-xs font-bold rounded-xl h-9 px-4 border-slate-300"
                >
                  ยกเลิก
                </Button>
                <Button
                  type="submit"
                  className="bg-blue-700 hover:bg-blue-800 text-white font-bold text-xs rounded-xl h-9 px-5 shadow-xs cursor-pointer"
                >
                  บันทึกการมอบหมาย
                </Button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* 5. Automatic Receive Stamp Modal */}
      {showStampModal && selectedDoc && (
        <StampModal
          isOpen={showStampModal}
          onClose={() => setShowStampModal(false)}
          documentId={selectedDoc.id}
          documentTitle={selectedDoc.title}
          regNo={selectedDoc.regNo}
          regDate={selectedDoc.regDate}
          regTime={selectedDoc.regTime}
          onStampSuccess={() => {
            const updated = {
              ...selectedDoc,
              status: "stamped" as IncomingStatus,
              timeline: [
                ...selectedDoc.timeline,
                {
                  action: "ประทับตรารับหนังสือ",
                  time: "เมื่อสักครู่",
                  actor: "ระบบสารบรรณอัตโนมัติ (E-Stamp)",
                  note: `ประทับตรายางรับเลข ${selectedDoc.regNo} ที่มุมบนขวา`,
                },
              ],
            };
            setDocuments((prev) => prev.map((d) => (d.id === selectedDoc.id ? updated : d)));
            setSelectedDoc(updated);
          }}
        />
      )}

      {/* 6. AI OCR Assistant Modal */}
      {showAiAssistantModal && (
        <AiAssistantModal
          isOpen={showAiAssistantModal}
          onClose={() => setShowAiAssistantModal(false)}
          onConfirmExtraction={(aiData) => {
            setFormData((prev) => ({
              ...prev,
              docNo: aiData.docNo || prev.docNo,
              docDate: aiData.docDate || prev.docDate,
              fromOrg: aiData.fromOrg || prev.fromOrg,
              toOrg: aiData.toOrg || prev.toOrg,
              title: aiData.title || prev.title,
              content: aiData.summary || prev.content,
              targetDept: aiData.suggestedDept || prev.targetDept,
            }));
            setShowCreateModal(true);
          }}
        />
      )}

      {/* 7. Full-Screen Immersion Endorsement Studio Workspace */}
      {activeWorkspaceDoc && (
        <DocumentViewerWorkspace
          document={activeWorkspaceDoc}
          onClose={() => setActiveWorkspaceDoc(null)}
        />
      )}
    </div>
  );
}
